### ISSUE TITLE
Discrepancy with respect to OTel semantics in RabbitMq Span

### ISSUE THREAD

**Issue by rish691** [hypertrace/javaagent#156]
Setup: Traceshop application instrumentation with HT java agent

Routing key which is a required key for RabbitMq backend, is missing in the span event for rabbitmq request from    shipitservice (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#rabbitmq)
Span kind is missing in the span event for rabbitmq request from login service & user service . A span event is considered as backend if it is an Exit span & it is a leaf span. Missing span kind  causes the span to be not considered for backend resolution. (spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#span-kind)

cc @pavolloffay 

[rabbitmq-span-event.zip](https://github.com/hypertrace/javaagent/files/5651178/rabbitmq-span-event.zip)

**Comment by pavolloffay** [comment]
> Routing key which is a required key for RabbitMq backend, is missing in the span event for rabbitmq request from shipitservice (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#rabbitmq)

The routing key attribute is added only if it is not empty:

>RabbitMQ
In RabbitMQ, the destination is defined by an exchange and a routing key. messaging.destination MUST be set to the name of the exchange. This will be an empty string if the default exchange is used. The routing key MUST be provided to the attribute messaging.rabbitmq.routing_key, unless it is empty.

The implementation looks correct:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/rabbitmq-2.7/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/rabbitmq/RabbitTracer.java#L114

**Comment by rish691** [comment]
Right, the routing key for `shipitservice` rabbitmq event is present when instrumented with old java agent.

https://app-dev.traceable.ai/backends/backend/d1912eb7-5745-31a6-9e7b-bc63397ee3e6/traces?time=1h&filter=tags_ckv_servicename%253Ashipitservice

<img width="1240" alt="Screenshot 2020-12-07 at 1 40 48 PM" src="https://user-images.githubusercontent.com/6513075/101325593-05494280-3892-11eb-8d55-6a837f407e77.png">

**Comment by pavolloffay** [comment]
> Span kind is missing in the span event for rabbitmq request from login service & user service . A span event is considered as backend if it is an Exit span & it is a leaf span. Missing span kind causes the span to be not considered for backend resolution. (spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#span-kind)

The rabbitmq instrumentation sets explicitly the span kind to client/producer https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/rabbitmq-2.7/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/rabbitmq/RabbitTracer.java#L36 

or consumer https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/rabbitmq-2.7/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/rabbitmq/RabbitTracer.java#L80

I assume the span kind gets lost somewhere in the conversion process. Our java agent uses Zipkin exporter and exports data to OC service wich converts data to OpenCensus and then to Jaeger.

**Comment by pavolloffay** [comment]
The routing key seems to be present in all cases when it makes sense e.g. `amqp.command=channel.open` does not have the attribute bc there is no routing in this case.

The missing span kind is because the opencensus-service (used by HT platform) does not recognize `producer` and `consumer` types https://github.com/hypertrace/opencensus-service/blob/main/receiver/zipkinreceiver/trace_receiver.go#L514. These types are not defined in OC proto. As a workaround I will put them directly into attributes.

**Comment by pavolloffay** [comment]
Done in the collector
