### ISSUE TITLE
GRPC Instrumentation not adding rpc.body to spans

### ISSUE THREAD

**Issue by shashank11p** [hypertrace/javaagent#313]
The GRPC instrumentation is not able to add rpc.request.body and rpc.response.body attributes to spans as the protobuf classes are shaded in the javaagent so the instrumentation looks for shaded classes, while during runtime the actual classes are used. 

So we should not shade the protobuf dependencies in javaagent. But javaagent also needs to have protobuf dependency for config. So we need to have the protobuf in javaagent to be in agentClassLoader, and do not shade it so that GRPC instrumentation works.

**Comment by pavolloffay** [comment]
We should also include gRPC in our smoke tests and test the payload capture.
